[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=64.0.0"]

[project]
authors = [{ name = "Otavio Napoli", email = "otavio.napoli@gmail.com" }]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
description = "Self supervised learning tools"
keywords = ["ssl_tools", "self supervised learning", "machine learning"]
license = { file = "LICENSE" }
name = "ssl_tools"
readme = "README.md"
requires-python = ">=3.8"
version = "0.0.1-dev"

dependencies = [
    "ipywidgets",
    "jsonargparse[all]",
    "librep@git+https://github.com/discovery-unicamp/hiaac-librep.git@0.0.4-dev",
    "lightly",
    "lightning",
<<<<<<< HEAD
    "librep@git+https://github.com/discovery-unicamp/hiaac-librep.git@0.0.4-dev",
    "scipy",
    "plotly",
=======
>>>>>>> refs/remotes/origin/main
    "numpy",
    "pandas",
    "plotly",
    "PyYAML",
    "rich",
    "scipy",
    "statsmodels",
    "torch",
    "zarr",
]

[project.optional-dependencies]
dev = ["mock", "pytest", "black", "isort"]
docs = ["sphinx", "sphinx-rtd-theme", "sphinx-autodoc-typehints", "sphinx-argparse", "sphinx", "sphinx-autoapi", "nbsphinx", "pandoc", "Ipython"]

[project.urls]

"Bug Tracker" = "https://github.com/otavioon/ssl_tools/issues"
"Homepage" = "https://github.com/otavioon/ssl_tools"

[tool.setuptools]
<<<<<<< HEAD
py-modules = ["ssl_tools"]

=======
py-modules = ["ssl_tools"]
>>>>>>> refs/remotes/origin/main
